###
GET http://localhost:5005/auth

###
POST http://localhost:5005/auth/register
Content-Type: application/json

{
    "username": "Will",
    "password": "Foxtrot5"
}

###
POST http://localhost:5005/auth/login
Content-Type: application/json

{
    "username":  "Chris",
    "password": "Foxtrot5"
}
